{:title "Exception (part 2)"
:layout :post
:date "2015-07-04"}

Semasa membuat input/output, kita mesti membuat _exception handling_.
Jika perasan, semua class yang terlibat dengan input/output perlu
ditutup selepas digunakan. Contohnya menggunakan method _‘close()’_
seperti berikut:

[source,java]
----
package essential;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class InputDariFile {

    public static void main(String[] args) throws IOException {

        BufferedReader reader =null;
        try {
            reader = new BufferedReader(new FileReader("cubaan.txt"));

            String input;

            while ((input = reader.readLine()) != null) {
                System.out.println(input);
            }
        } finally {
            reader.close();
        }
    }
}
----

Bagi mengelakkan programmer lupa untuk menutup semula class tersebut,
Java menyediakan satu lagi jenis _exception handling_ iaitu
_try-with-resources_.

=== try-with-resources

Dalam _try-with-resources_, class yang digunakan untuk input/output
diletakkan di dalam kurungan selepas _‘try’_:

[source,java]
----
package essential;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class InputDariFile {
    public static void main(String[] args) {
        try (BufferedReader reader = new BufferedReader(new FileReader("cubaan.txt"))) {

            String input;

            while ((input = reader.readLine()) != null) {
                System.out.println(input);
            }
        } catch (IOException ex) {
            Logger.getLogger(InputDariFile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
----

Jadi, Java akan tutup secara automatik class BufferedReader selepas
digunakan walaupun kita tidak meletakkan method _‘close()’_.

Keyword _catch_, _finally_, dan _throws_ masih boleh digunakan seperti
biasa.
